name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Upload Release Assets
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '25'
          distribution: 'adopt'

      - name: Build & Test
        run: mvn package

      - name: Remove non-final shaded jars
        run: rm -f target/original-*.jar

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE.txt
            target/*.jar
